# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_ast_utils.ipynb.

# %% auto 0
__all__ = ['extract_python_elements']

# %% ../nbs/01_ast_utils.ipynb 2
from tree_sitter import Language, Parser
import tree_sitter_python as tspython

# %% ../nbs/01_ast_utils.ipynb 3
def extract_python_elements(source_code: str):
    """
    Extract identifiers, comments, and strings from Python source code using Tree-sitter.
    Returns a dictionary with keys: 'identifiers', 'comments', 'strings'.
    Each value is a list of Tree-sitter nodes.
    """
    language = Language(tspython.language())
    parser = Parser(language)

    tree = parser.parse(source_code.encode("utf8"))
    root_node = tree.root_node

    result = {
        'identifiers': [],
        'comments': [],
        'strings': []
    }

    def traverse(node):
        if node.type == 'identifier':
            result['identifiers'].append(node)
        elif node.type == 'comment':
            result['comments'].append(node)
        elif node.type == 'string':
            result['strings'].append(node)

        for child in node.children:
            traverse(child)

    traverse(root_node)
    return result

