# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_pos_utils.ipynb.

# %% auto 0
__all__ = ['UNIVERSAL_SEMANTIC_TAGS', 'load_spacy_model', 'count_pos_tags', 'get_all_pos_types']

# %% ../nbs/02_pos_utils.ipynb 2
import spacy
from collections import Counter
import subprocess
import importlib.util

# %% ../nbs/02_pos_utils.ipynb 3
UNIVERSAL_SEMANTIC_TAGS = ['NOUN', 'PROPN', 'VERB', 'ADJ', 'ADV', 'NUM', 'INTJ']

# %% ../nbs/02_pos_utils.ipynb 4
def load_spacy_model(model_name="en_core_web_sm"):
    try:
        return spacy.load(model_name)
    except OSError:
        print(f"Downloading spaCy model '{model_name}'...")
        subprocess.run(["python", "-m", "spacy", "download", model_name], check=True)
        return spacy.load(model_name)

# %% ../nbs/02_pos_utils.ipynb 5
def count_pos_tags(text: str) -> dict:
    nlp = load_spacy_model()
    doc = nlp(text)
    pos_counts = Counter(token.pos_ for token in doc)
    return dict(pos_counts)

# %% ../nbs/02_pos_utils.ipynb 6
def get_all_pos_types(model_name="en_core_web_sm") -> list:
    try:
        nlp = spacy.load(model_name)
    except OSError:
        import subprocess
        subprocess.run(["python", "-m", "spacy", "download", model_name], check=True)
        nlp = spacy.load(model_name)

    return list(nlp.get_pipe("tagger").labels)

