# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_semantic_preserving_transformations.ipynb.

# %% auto 0
__all__ = ['FirstLetterVariableRenamer', 'rename_variable_1', 'CodeBERTVariableRenamer', 'rename_variable_2',
           'RelationalExpressionSwitcher', 'switch_relation', 'AugAssignTransformer', 'add_2_equal', 'infix_dividing',
           'SwitchEqualExpTransformer', 'switch_equal_exp']

# %% ../nbs/00_semantic_preserving_transformations.ipynb 3
import libcst as cst
from redbaron import RedBaron
import copy
import ast
import re
from libcst.metadata import ScopeProvider, MetadataWrapper, ParentNodeProvider
from transformers import RobertaTokenizer, RobertaForMaskedLM, pipeline
from libcst import (
    SimpleStatementLine,
    Assign,
    AssignTarget,
    BinaryOperation,
    Name,
    FlattenSentinel,
    TrailingWhitespace,
    Newline,
    SimpleWhitespace,
)


# %% ../nbs/00_semantic_preserving_transformations.ipynb 5
###############################################################################
# Transformer for rename_variable_1: First-letter renaming
###############################################################################

class FirstLetterVariableRenamer(cst.CSTTransformer):
    """
    A simple transformer that replaces variable names with their first letter.
    WARNING: This may lead to collisions if two identifiers share the same first letter.
    """
    METADATA_DEPENDENCIES = (ScopeProvider,)

    def leave_Name(
        self, original_node: cst.Name, updated_node: cst.Name
    ) -> cst.BaseExpression:
        # Only replace names longer than one character
        if len(updated_node.value) > 1:
            new_val = updated_node.value[0]
            return updated_node.with_changes(value=new_val)
        return updated_node

def rename_variable_1(code: str) -> str:
    """
    Replace variable names (and other identifiers) with their first letter.
    
    Args:
        code: A string containing Python source code.
    
    Returns:
        The transformed code as a string.
    """
    module = cst.parse_module(code)
    wrapper = MetadataWrapper(module)
    new_module = wrapper.visit(FirstLetterVariableRenamer())
    return new_module.code

# %% ../nbs/00_semantic_preserving_transformations.ipynb 6
###############################################################################
# Transformer for rename_variable_2: CodeBERT-based renaming for variables only
###############################################################################

class CodeBERTVariableRenamer(cst.CSTTransformer):
    """
    Transformer that uses CodeBERT's fill-mask capability to generate new names,
    but only for variable names. It will update every occurrence (i.e. all references)
    of the same variable (as determined by its binding) while skipping:
      - function definitions,
      - class definitions,
      - function calls,
      - attribute accesses, and
      - import statements.
    
    For each identifier (that is not skipped) longer than one character, a dummy code context is
    constructed and CodeBERT is used to predict a suitable replacement. If the predicted token is
    not a valid identifier, it falls back to using the first letter.
    
    NOTE: This is an experimental approach and may result in unpredictable names.
    """
    # Request both scope and parent metadata.
    METADATA_DEPENDENCIES = (ScopeProvider, ParentNodeProvider)

    def __init__(self, model_name: str, cache_dir: str):
        # Load the tokenizer and model with the cache directory specified.
        model_tokenizer = RobertaTokenizer.from_pretrained(model_name, cache_dir=cache_dir)
        pre_trained_model = RobertaForMaskedLM.from_pretrained(model_name, cache_dir=cache_dir)
        # Initialize the fill-mask pipeline.
        self.fill_mask = pipeline('fill-mask', model=pre_trained_model, tokenizer=model_tokenizer)
        # Cache substitutions keyed by a variable’s binding (or fallback to its name).
        self.substitutions = {}

    def leave_Name(self, original_node: cst.Name, updated_node: cst.Name) -> cst.BaseExpression:
        parent = self.get_metadata(ParentNodeProvider, original_node)

        # Skip renaming for import-related nodes.
        if isinstance(parent, (cst.Import, cst.ImportFrom, cst.ImportAlias)):
            return updated_node

        # Skip renaming for:
        # - The name of a function definition.
        # - The name of a class definition.
        # - The function being called.
        # - The attribute in an attribute access.
        if isinstance(parent, cst.FunctionDef) and parent.name == original_node:
            return updated_node
        if isinstance(parent, cst.ClassDef) and parent.name == original_node:
            return updated_node
        if isinstance(parent, cst.Call) and parent.func == original_node:
            return updated_node
        if isinstance(parent, cst.Attribute) and parent.attr == original_node:
            return updated_node

        # Retrieve the scope for this node and try to obtain its binding.
        try:
            scope = self.get_metadata(ScopeProvider, original_node)
            binding = scope.get_binding(original_node)
        except Exception:
            binding = None

        # Use the binding’s id as a key if available; otherwise, fallback to the name string.
        key = id(binding) if binding is not None else updated_node.value

        # Process only if the identifier is longer than one character.
        if len(updated_node.value) > 1:
            if key not in self.substitutions:
                original_name = updated_node.value
                # Create an enhanced dummy context.
                # This context provides extra semantic hints and only one <mask> token.
                dummy_context = (
                    f"def dummy({original_name}):\n"
                    f"    # This variable is used in a numerical computation. Suggest a clearer name.\n"
                    f"    result = {original_name} * 2\n"
                    f"    return <mask>"
                )
                try:
                    results = self.fill_mask(dummy_context)
                except Exception as e:
                    print(f"CodeBERT error for '{original_name}': {e}")
                    self.substitutions[key] = original_name[0]
                    return updated_node.with_changes(value=self.substitutions[key])
                
                if results:
                    # Check if the results are nested (i.e., if there are multiple mask tokens)
                    if isinstance(results[0], list):
                        # Use the first candidate from the first mask
                        new_name = results[0][0]["token_str"].strip()
                    else:
                        new_name = results[0]["token_str"].strip()
                    # Ensure the new name is a valid identifier.
                    if not new_name.isidentifier():
                        new_name = original_name[0]
                else:
                    new_name = original_name[0]
                self.substitutions[key] = new_name
            return updated_node.with_changes(value=self.substitutions[key])
        return updated_node

def rename_variable_2(code: str, model_name: str, cache_dir: str) -> str:
    """
    Replace variable names (and only variable names) using suggestions from CodeBERT,
    updating all references for a given variable binding.
    
    Args:
        code: A string containing Python source code.
        model_name: The name of the CodeBERT model.
        cache_dir: Directory path for caching the model.
    
    Returns:
        The transformed code as a string.
    """
    module = cst.parse_module(code)
    wrapper = cst.MetadataWrapper(module)
    new_module = wrapper.visit(CodeBERTVariableRenamer(model_name, cache_dir))
    return new_module.code


# %% ../nbs/00_semantic_preserving_transformations.ipynb 8
###############################################################################
# Transformer for switch_relation: Relational expression switching
###############################################################################

class RelationalExpressionSwitcher(cst.CSTTransformer):
    """
    Transformer that switches relational expressions.

    For example, transforms:
        a < b  -->  b > a

    Only comparisons with a single relational operator are transformed.
    """
    def leave_Comparison(self, original_node: cst.Comparison, updated_node: cst.Comparison) -> cst.BaseExpression:
        # Only handle comparisons with exactly one comparison target.
        if len(updated_node.comparisons) != 1:
            return updated_node

        comp = updated_node.comparisons[0]

        # Mapping of relational operators to their inverted counterparts.
        mapping = {
            cst.LessThan: cst.GreaterThan,
            cst.GreaterThan: cst.LessThan,
            cst.LessThanEqual: cst.GreaterThanEqual,
            cst.GreaterThanEqual: cst.LessThanEqual,
            # For equality and inequality the operator remains the same when operands are swapped.
            cst.Equal: cst.Equal,
            cst.NotEqual: cst.NotEqual,
            cst.Is: cst.Is,
            cst.IsNot: cst.IsNot,
        }

        op_type = type(comp.operator)
        if op_type in mapping:
            new_operator = mapping[op_type]()
        else:
            new_operator = comp.operator

        # Swap the operands:
        # - New left operand becomes the original comparator.
        # - The new comparison target is built using the original left operand.
        new_left = comp.comparator
        new_comparison = cst.ComparisonTarget(
            operator=new_operator,
            comparator=updated_node.left
        )

        return updated_node.with_changes(left=new_left, comparisons=[new_comparison])

def switch_relation(code: str) -> str:
    """
    Transform relational expressions by switching operands and inverting operators.

    For example, 'a < b' becomes 'b > a'.

    Args:
        code: Python source code as a string.

    Returns:
        The transformed code as a string.
    """
    module = cst.parse_module(code)
    wrapper = MetadataWrapper(module)
    new_module = wrapper.visit(RelationalExpressionSwitcher())
    return new_module.code


# %% ../nbs/00_semantic_preserving_transformations.ipynb 9
###############################################################################
# Transformer for unary_2_add: Converting augmented assignments to explicit assignments
###############################################################################

class AugAssignTransformer(cst.CSTTransformer):
    """
    Transformer that converts augmented assignments (e.g., i += 1) into equivalent
    explicit assignments (e.g., i = i + 1).
    """
    def leave_AugAssign(
        self, original_node: cst.AugAssign, updated_node: cst.AugAssign
    ) -> cst.BaseSmallStatement:
        # Map the augmented assignment operator class names to their corresponding binary operator classes.
        operator_mapping = {
            "AddAssign": cst.Add,
            "SubtractAssign": cst.Subtract,
            "MultiplyAssign": cst.Multiply,
            "DivideAssign": cst.Divide,
            "ModuloAssign": cst.Modulo,
            "PowerAssign": cst.Power,
            "FloorDivideAssign": cst.FloorDivide,
            "BitAndAssign": cst.BitAnd,
            "BitOrAssign": cst.BitOr,
            "BitXorAssign": cst.BitXor,
            "LeftShiftAssign": cst.LeftShift,
            "RightShiftAssign": cst.RightShift,
        }
        # Use the operator's class name (e.g., "AddAssign") as the key.
        op_class_name = updated_node.operator.__class__.__name__
        binary_operator_class = operator_mapping.get(op_class_name, None)
        if binary_operator_class is None:
            # If the operator isn't recognized, leave the node unchanged.
            return updated_node

        # Construct a binary operation: <target> <binary_operator> <value>
        new_binary_op = cst.BinaryOperation(
            left=updated_node.target,
            operator=binary_operator_class(),
            right=updated_node.value,
        )
        # Construct an assignment: <target> = (<target> <binary_operator> <value>)
        new_assign = cst.Assign(
            targets=[cst.AssignTarget(target=updated_node.target)],
            value=new_binary_op,
        )
        return new_assign

def add_2_equal(code: str) -> str:
    """
    Transform augmented assignments (e.g., i += 1) into explicit assignments (e.g., i = i + 1).

    Args:
        code: Python source code as a string.

    Returns:
        The transformed code as a string.
    """
    # Parse the code into a CST.
    module = cst.parse_module(code)
    # Wrap the module to preserve formatting.
    wrapper = MetadataWrapper(module)
    # Visit the tree with our AugAssignTransformer.
    new_module = wrapper.visit(AugAssignTransformer())
    return new_module.code

# %% ../nbs/00_semantic_preserving_transformations.ipynb 10
def infix_dividing(code: str) -> str:
    """
    Transform assignments of the form:
        x = L op1 R
    where R is itself a binary expression and its operator has higher precedence than op1,
    by extracting R into a temporary variable.

    For example, the code:
        x = a + b * c  # comment on assignment
    is transformed into:
        temp = b * c
        x = a + temp  # comment on assignment

    All comments and formatting are preserved.

    Args:
        code: The original Python source code.

    Returns:
        The transformed source code as a string.
    """
    red = RedBaron(code)

    # Precedence mapping: operators as strings mapped to a numeric value.
    precedence_map = {
        "+": 1,
        "-": 1,
        "*": 2,
        "/": 2,
        "%": 2,
        "**": 3,
    }

    # Iterate over all assignment nodes.
    for assign in red.find_all("AssignmentNode"):
        # Check that the right-hand side is a binary operator node.
        if assign.value.type != "binary_operator":
            continue

        outer = assign.value
        # Use dumps() to get the string form and split it into tokens.
        tokens_outer = outer.dumps().split()
        if len(tokens_outer) < 3:
            continue  # not an expression like L op R

        # Assume the outer operator is the second token.
        op1 = tokens_outer[1]

        # Access the right-hand side (R). In RedBaron, for a binary operator node:
        #   - .first gives the left operand,
        #   - .second gives the right operand.
        R = outer.second

        # Only proceed if R is itself a binary operator node.
        if R.type != "binary_operator":
            continue

        tokens_R = R.dumps().split()
        if len(tokens_R) < 3:
            continue
        # Assume the operator in R is the second token.
        op_R = tokens_R[1]

        # Check precedence: extract if precedence(op_R) > precedence(op1)
        if precedence_map.get(op_R, 0) <= precedence_map.get(op1, 0):
            continue

        # Build a temporary assignment string: "temp = " + (dump of R)
        temp_assign_str = "temp = " + R.dumps()
        # Create a new node from the string.
        temp_assignment = RedBaron(temp_assign_str)[0]

        # Insert the temporary assignment before the current assignment.
        # Since assign.parent is a NodeList, we get the index of 'assign'
        # and then insert 'temp_assignment' at that index.
        parent_list = assign.parent
        index = parent_list.index(assign)
        parent_list.insert(index, temp_assignment)

        # Replace the original R (the right-hand side of the outer binary expression)
        # with the temporary variable "temp". Simply assigning "temp" creates a NameNode.
        outer.second = "temp"

    # Return the transformed code as a string.
    return red.dumps()


# %% ../nbs/00_semantic_preserving_transformations.ipynb 11
class SwitchEqualExpTransformer(cst.CSTTransformer):
    """
    Transformer that switches the left and right expressions of a simple equality comparison.
    
    For a comparison of the form:
    
        a == b
    
    where the Comparison node has:
      - left: the left-hand side expression, and
      - comparisons: a list with a single ComparisonTarget whose operator is Equal and
        whose comparator is the right-hand side expression,
        
    this transformer returns a new Comparison node equivalent to:
    
        b == a
        
    The operator remains unchanged. Chained comparisons (with more than one operator)
    are not modified.
    """
    def leave_Comparison(
        self, original_node: cst.Comparison, updated_node: cst.Comparison
    ) -> cst.BaseExpression:
        # Process only simple (non-chained) comparisons.
        if len(updated_node.comparisons) != 1:
            return updated_node

        comp_target = updated_node.comparisons[0]
        # Check that the operator is an equality operator.
        if not isinstance(comp_target.operator, cst.Equal):
            return updated_node

        # Use copy.deepcopy to preserve formatting and any attached comments.
        new_left = copy.deepcopy(comp_target.comparator)
        new_comparator = copy.deepcopy(updated_node.left)

        # Create a new ComparisonTarget node with the same operator.
        new_comp_target = comp_target.with_changes(comparator=new_comparator)
        
        # Build a new Comparison node with swapped sides.
        return updated_node.with_changes(
            left=new_left,
            comparisons=[new_comp_target]
        )

def switch_equal_exp(code: str) -> str:
    """
    Switch the two expressions on both sides of a simple equality (==) comparison.
    
    For example, given the code:
    
        a == b
        
    the transformation produces:
    
        b == a
        
    Only simple (non‑chained) equality comparisons are modified; all comments,
    whitespace, and other code remain unchanged.
    
    Args:
        code: A string containing the original Python source code.
    
    Returns:
        A string containing the transformed Python source code.
    """
    # Parse the code into a CST.
    module = cst.parse_module(code)
    # Wrap the module; metadata is not required for this transformation.
    wrapper = MetadataWrapper(module)
    # Apply our transformer.
    new_module = wrapper.visit(SwitchEqualExpTransformer())
    # Return the modified code.
    return new_module.code

